# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ui_0fUAbcjcgiAtTn9BRtwiUFO2JXeOe
"""

cv_code = '''
import streamlit as st

st.set_page_config(page_title="CV de María Fe", page_icon="📄")

st.title("💼 Currículum de María Fe Lidia Jacha La Pierre")

st.subheader("🎓 Estudiante de Comunicación Audiovisual")
st.write("Estudiante de tercer año de la carrera de Comunicación Audiovisual en la Pontificia Universidad Católica del Perú. Becaria Lucet por excelencia académica. Soy proactiva, responsable, organizada y carismática. Me gusta tomar la iniciativa para crear nuevos proyectos que se ajusten a los intereses y necesidades.")

st.header("📞 Información Personal")
st.write("📧 Correo: mariafejachalapierre@gmail.com")
st.write("📱 Teléfono: 923 315 527")

st.header("🎓 Educación")
st.write("**Pontificia Universidad Católica del Perú**")
st.write("Carrera: Comunicación Audiovisual")
st.write("Duración: Marzo 2023 - Actualidad")
st.write("🏅 Logro: Becaria Lucet por excelencia académica")

st.header("🛠️ Habilidades")
st.write("- Microsoft Office: Word, PowerPoint y Excel")
st.write("- Trabajo en equipo")
st.write("- Liderazgo")

st.header("🌍 Idiomas")
st.write("- Español (nativo)")
st.write("- Inglés (avanzado)")
st.write("- Italiano (avanzado)")

st.header("💼 Experiencia Laboral")
st.write("**Apoyo administrativo / Guía PUCP - Oficina de Admisión**")
st.write("📅 Marzo 2024 - Marzo 2025")
st.write("- Representar a la PUCP en diferentes instituciones educativas de nivel básico")

st.header("🤝 Voluntariado")
st.write("**Community Manager**")
st.write("📅 Noviembre 2024 - Actualidad")
st.write("- Planificación de contenidos")
st.write("- Análisis de estadísticas")
st.write("- Diseño de post para redes sociales")

st.header("✨ Intereses")
st.write("- Escritura")
st.write("- Fotografía")
st.write("- Arte")

st.write("---")
st.caption("Aplicación creada con ❤️ usando Streamlit.")
'''

with open("cv_app.py", "w") as f:
    f.write(cv_code)

print("✅ El archivo 'cv_app.py' ha sido creado correctamente.")